Repository Joshua-Ashton/website, pull requests merged in 2020-09, with the labels that each got.

#1 website read me init
  README.md
Labels: enhancement, question

#2 improve documentation
  LICENSE.md/LICENSE.md
  README.md
Labels: help wanted

#4 site
  .gitignore
  site/assets/images/cow.gif
  site/index.html
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix
